/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package collegemangementsystem;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.ImageIcon;
import net.proteanit.sql.DbUtils;
/**
 *
 * @author akki
 */
public class View extends javax.swing.JFrame {

    /**
     * Creates new form View
     */
    public View() {
        initComponents();
        this .setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        plMain2 = new javax.swing.JPanel();
        plSideMenu2 = new javax.swing.JPanel();
        btnViewStudent = new javax.swing.JButton();
        btnViewTeacher2 = new javax.swing.JButton();
        btnViewCourse = new javax.swing.JButton();
        btnViewAdmin = new javax.swing.JButton();
        btnBack3 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblViewCourses = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblViewTeacher = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblViewStudent = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblViewAdmin = new javax.swing.JTable();
        lblImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        plMain2.setBackground(new java.awt.Color(255, 255, 255));

        plSideMenu2.setBackground(new java.awt.Color(102, 255, 102));

        btnViewStudent.setBackground(new java.awt.Color(0, 102, 102));
        btnViewStudent.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        btnViewStudent.setForeground(new java.awt.Color(255, 255, 255));
        btnViewStudent.setText("VIEW STUDENTS");
        btnViewStudent.setBorder(null);
        btnViewStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewStudentActionPerformed(evt);
            }
        });

        btnViewTeacher2.setBackground(new java.awt.Color(0, 102, 102));
        btnViewTeacher2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        btnViewTeacher2.setForeground(new java.awt.Color(255, 255, 255));
        btnViewTeacher2.setText("VIEW TEACHERS");
        btnViewTeacher2.setBorder(null);
        btnViewTeacher2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewTeacher2ActionPerformed(evt);
            }
        });

        btnViewCourse.setBackground(new java.awt.Color(0, 102, 102));
        btnViewCourse.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        btnViewCourse.setForeground(new java.awt.Color(255, 255, 255));
        btnViewCourse.setText("VIEW COURSES");
        btnViewCourse.setBorder(null);
        btnViewCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewCourseActionPerformed(evt);
            }
        });

        btnViewAdmin.setBackground(new java.awt.Color(0, 102, 102));
        btnViewAdmin.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        btnViewAdmin.setForeground(new java.awt.Color(255, 255, 255));
        btnViewAdmin.setText("VIEW ADMIN ");
        btnViewAdmin.setBorder(null);
        btnViewAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewAdminActionPerformed(evt);
            }
        });

        btnBack3.setBackground(new java.awt.Color(0, 102, 102));
        btnBack3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/back.png"))); // NOI18N
        btnBack3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout plSideMenu2Layout = new javax.swing.GroupLayout(plSideMenu2);
        plSideMenu2.setLayout(plSideMenu2Layout);
        plSideMenu2Layout.setHorizontalGroup(
            plSideMenu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plSideMenu2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(plSideMenu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnViewStudent, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                    .addComponent(btnViewCourse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnViewAdmin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnViewTeacher2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(plSideMenu2Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(btnBack3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        plSideMenu2Layout.setVerticalGroup(
            plSideMenu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plSideMenu2Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(btnBack3)
                .addGap(30, 30, 30)
                .addComponent(btnViewCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnViewTeacher2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnViewStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnViewAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseClicked(evt);
            }
        });

        tblViewCourses.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblViewCourses.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblViewCoursesMouseClicked(evt);
            }
        });
        tblViewCourses.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tblViewCoursesKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblViewCourses);

        jTabbedPane1.addTab("VIEW COURSES", jScrollPane1);

        tblViewTeacher.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblViewTeacher.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblViewTeacherMouseClicked(evt);
            }
        });
        tblViewTeacher.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tblViewTeacherKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(tblViewTeacher);

        jTabbedPane1.addTab("VIEW TEACHERS", jScrollPane2);

        tblViewStudent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblViewStudent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblViewStudentMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblViewStudent);

        jTabbedPane1.addTab("VIEW STUDENTS", jScrollPane3);

        tblViewAdmin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(tblViewAdmin);

        jTabbedPane1.addTab("VIEW ADMIN ", jScrollPane4);

        lblImage.setMaximumSize(new java.awt.Dimension(100, 100));
        lblImage.setMinimumSize(new java.awt.Dimension(100, 100));
        lblImage.setPreferredSize(new java.awt.Dimension(100, 100));

        javax.swing.GroupLayout plMain2Layout = new javax.swing.GroupLayout(plMain2);
        plMain2.setLayout(plMain2Layout);
        plMain2Layout.setHorizontalGroup(
            plMain2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plMain2Layout.createSequentialGroup()
                .addComponent(plSideMenu2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(plMain2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(plMain2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 871, Short.MAX_VALUE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, plMain2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(142, 142, 142))))
        );
        plMain2Layout.setVerticalGroup(
            plMain2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(plSideMenu2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(plMain2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(plMain2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(plMain2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1073, 556));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewStudentActionPerformed
        // TODO add your handling code here:
        lblImage.setIcon(null);
        jTabbedPane1.setSelectedIndex(2);
        Connection con;
        try {
            con=CreateConnection.getObject();
            Statement smt=con.createStatement();
            String sqlquery="Select * from student";
            
            ResultSet rs=smt.executeQuery(sqlquery);
            tblViewStudent.setModel(DbUtils.resultSetToTableModel(rs));
            con.close();
        }
        catch (Exception ex) {
            System.err.println("Got an exception! ");
            System.err.println(ex.getMessage());
        }
    }//GEN-LAST:event_btnViewStudentActionPerformed

    private void btnViewTeacher2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewTeacher2ActionPerformed
        // TODO add your handling code here:
        lblImage.setIcon(null);
        jTabbedPane1.setSelectedIndex(1);
         Connection con;
        try {
            con=CreateConnection.getObject();
            Statement smt=con.createStatement();
            String sqlquery="Select * from teacher";
            ResultSet rs=smt.executeQuery(sqlquery);
            tblViewTeacher.setModel(DbUtils.resultSetToTableModel(rs));
            con.close();
        }
        catch (Exception ex) {
            System.err.println("Got an exception! ");
            System.err.println(ex.getMessage());
        }
    }//GEN-LAST:event_btnViewTeacher2ActionPerformed

    private void btnViewCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewCourseActionPerformed
        // TODO add your handling code here:
        lblImage.setIcon(null);
        jTabbedPane1.setSelectedIndex(0);
        Connection con;
        try {
            con=CreateConnection.getObject();
            Statement smt=con.createStatement();
            String sqlquery="Select * from course";
            
            ResultSet rs=smt.executeQuery(sqlquery);
            tblViewCourses.setModel(DbUtils.resultSetToTableModel(rs));
            con.close();
        }
        catch (Exception ex) {
            System.err.println("Got an exception! ");
            System.err.println(ex.getMessage());
        }
    }//GEN-LAST:event_btnViewCourseActionPerformed

    private void btnViewAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewAdminActionPerformed
        // TODO add your handling code here:
        lblImage.setIcon(null);
        jTabbedPane1.setSelectedIndex(3);
        Connection con;
        try {
            con=CreateConnection.getObject();
            Statement smt=con.createStatement();
            String sqlquery="Select * from signup";
            
            ResultSet rs=smt.executeQuery(sqlquery);
            tblViewAdmin.setModel(DbUtils.resultSetToTableModel(rs));
            con.close();
        }
        catch (Exception ex) {
            System.err.println("Got an exception! ");
            System.err.println(ex.getMessage());
        }
    }//GEN-LAST:event_btnViewAdminActionPerformed

    private void btnBack3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack3ActionPerformed
        // TODO add your handling code here:
        new Edit();
        this.dispose();
    }//GEN-LAST:event_btnBack3ActionPerformed

    private void tblViewCoursesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblViewCoursesMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tblViewCoursesMouseClicked

    private void tblViewTeacherMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblViewTeacherMouseClicked
        // TODO add your handling code here:
        int row=tblViewTeacher.getSelectedRow();
        int col=tblViewTeacher.getSelectedColumn();
        int id=Integer.parseInt(tblViewTeacher.getModel().getValueAt(row,0).toString());
        System.out.println("123123123");
        Connection con;
        try {
            con=CreateConnection.getObject();
            Statement smt=con.createStatement();
            String sqlquery="Select Photo from teacher where TID=?";
            PreparedStatement pst = con.prepareStatement(sqlquery);
            pst.setInt(1,id);
            ResultSet rs=pst.executeQuery();
            rs.next();
            byte[] image= rs.getBytes("Photo");
            format =new ImageIcon(image);
            lblImage.setIcon(format);
            System.out.println("+++++++++++++++");
            
            con.close();
        }
        catch (Exception ex) {
            System.err.println("Got an exception! ");
            System.err.println(ex.getMessage());
        }
    }//GEN-LAST:event_tblViewTeacherMouseClicked

    private void tblViewTeacherKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblViewTeacherKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tblViewTeacherKeyPressed

    private void tblViewStudentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblViewStudentMouseClicked
        // TODO add your handling code here:
        int row=tblViewStudent.getSelectedRow();
        int col=tblViewStudent.getSelectedColumn();
        int id=Integer.parseInt(tblViewStudent.getModel().getValueAt(row,0).toString());
        //System.out.println("FINALLY HERE");
        Connection con;
        try {
            con=CreateConnection.getObject();
            Statement smt=con.createStatement();
            String sqlquery="Select SPhoto from student where SID=?";
            PreparedStatement pst = con.prepareStatement(sqlquery);
            pst.setInt(1,id);
            ResultSet rs=pst.executeQuery();
            rs.next();
            byte[] image= rs.getBytes("SPhoto");
            format =new ImageIcon(image);
            lblImage.setIcon(format);
            System.out.println("+++++++++++++++");
            
            con.close();
        }
        catch (Exception ex) {
            System.err.println("Got an exception! ");
            System.err.println(ex.getMessage());
        }
    }//GEN-LAST:event_tblViewStudentMouseClicked

    private void tblViewCoursesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblViewCoursesKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tblViewCoursesKeyPressed

    private void jScrollPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack3;
    private javax.swing.JButton btnViewAdmin;
    private javax.swing.JButton btnViewCourse;
    private javax.swing.JButton btnViewStudent;
    private javax.swing.JButton btnViewTeacher2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblImage;
    private javax.swing.JPanel plMain2;
    private javax.swing.JPanel plSideMenu2;
    private javax.swing.JTable tblViewAdmin;
    private javax.swing.JTable tblViewCourses;
    private javax.swing.JTable tblViewStudent;
    private javax.swing.JTable tblViewTeacher;
    // End of variables declaration//GEN-END:variables
private ImageIcon format=null;
}
